title: 无讼法苑
description: 分享，极致生活！！！

url: http://www.wusong.me/

theme: donob

per_page: 7

# menu
menu:
  Archives: /archives/
  About: /about/

default_category: blog

user: fydy
repository: issue-blog

plugins:
  - acyort-rss
  - acyort-archives
  - acyort-paginator
  - acyort-toc

public_dir: public

authors:
  - fydy

timezone: Asia/Shanghai

language:

line_numbers:

order:

token: 8#aff904696956cce9371882f55e448b9b3a2793b

cache: true

rss: true

archives:
  per_page: 30
